[TAUTULLI]
API_ENDPOINT = "https://tautulli.jamesthrasher.io/api/v2"
API_KEY = "72ec27e852a24214b9d56884310033ab"
# Tautulli library 'section' for movies
SECTION_ID = 1


[PLEX_SERVER_SSH]
SERVER = "172.16.0.2"
PORT = 22
USERNAME = "admin"
PASSWORD = ""

[MISC]
# If `DEBUG`, movies will not be deleted but will log the files that would be if `DEBUG` is set to `False`
DEBUG = true
#Minimum number of days movie has not been watched to be deleted
DAYS = 10
# Root path for movies stored on Plex server
PLEX_MOVIE_ROOT = "/mnt/FreeNAS/Movies"
