[servers]
base_ip = "172.16.0.2"

[servers.radarr]
port = 7878
api_key = "683a12d24ebd4eaf80b7ec6ca8ca02e6"
api_route = "/api/v3"
status_endpoint = "/system/status"

[servers.sonarr]
port = 8989
api_key = "4cdf6b59d6754347a7b72592287e0c7d"
api_route = "/api"
status_endpoint = "/system/status"

[servers.tautulli]
port = 8181
api_key = "72ec27e852a24214b9d56884310033ab"
api_route = "/api/v2"
status_param = "server_status"

[servers.plex]
port = 32400
username = "preditechs"
password = "2G7RgV3rjDhm"